services:
  mysql:
    container_name: 'guide-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=FUTURA'
      - 'MYSQL_PASSWORD=Lafouine07'
      - 'MYSQL_ROOT_PASSWORD=Lafouine09$'
      - 'MYSQL_USER=ankillous'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:




















